// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuEaQQL49Ex40q05eicN7jkCM6G7VfFqQ',
    appId: '1:166676150095:web:1272156ba018ada6c5b73a',
    messagingSenderId: '166676150095',
    projectId: 'lostandfoundapp-32d9f',
    authDomain: 'lostandfoundapp-32d9f.firebaseapp.com',
    storageBucket: 'lostandfoundapp-32d9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAAxNAYENimFOdWDCLcqNMyMf2rRSW-_8',
    appId: '1:166676150095:android:84bd1c743ccbaff1c5b73a',
    messagingSenderId: '166676150095',
    projectId: 'lostandfoundapp-32d9f',
    storageBucket: 'lostandfoundapp-32d9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEDTanrxKVoVDcjh81c--GS3cxbHZkTzI',
    appId: '1:166676150095:ios:9b5b62aafd5f80b5c5b73a',
    messagingSenderId: '166676150095',
    projectId: 'lostandfoundapp-32d9f',
    storageBucket: 'lostandfoundapp-32d9f.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEDTanrxKVoVDcjh81c--GS3cxbHZkTzI',
    appId: '1:166676150095:ios:9b5b62aafd5f80b5c5b73a',
    messagingSenderId: '166676150095',
    projectId: 'lostandfoundapp-32d9f',
    storageBucket: 'lostandfoundapp-32d9f.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuEaQQL49Ex40q05eicN7jkCM6G7VfFqQ',
    appId: '1:166676150095:web:92b7815a00df4ad8c5b73a',
    messagingSenderId: '166676150095',
    projectId: 'lostandfoundapp-32d9f',
    authDomain: 'lostandfoundapp-32d9f.firebaseapp.com',
    storageBucket: 'lostandfoundapp-32d9f.firebasestorage.app',
  );
}
